# -*- coding: utf-8 -*-
"""mymodule

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTbuFMwUxCQnA81CNEBYq581zwvL5g0a
"""

def square(x):
    return x ** 2